apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.namespace }}-limit-range
  namespace: {{ .Values.namespace }}
spec:
  limits:
    - type: Container
      default:
        cpu: {{ .Values.limits.defaultLimitCpu }}
        memory: {{ .Values.limits.defaultLimitMemory }}
      defaultRequest:
        cpu: {{ .Values.limits.defaultRequestCpu }}
        memory: {{ .Values.limits.defaultRequestMemory }}
